# Generated by Django 2.1.5 on 2019-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workedYears', models.DecimalField(decimal_places=1, max_digits=3)),
                ('salaryBrutto', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
